### updates an existing patient entity
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "Vansh Patel how",
  "email": "test5@email.com",
  "address": "A11 Shahisundram2",
  "dateOfBirth": "1205-12-12"
}

###